### ISSUE TITLE
Date problem?

### ISSUE THREAD

**Issue by L0cutus** [sawhney17/logseq-calendars-plugin#1]
Hello!
I have set an event on 29/1/2022 Saturday on my google calendar but when i fetc it with the plugi it create a wrong journal date in the format yyyy/MM/dd EEEE but it put literally the "EEEE" string instead of the name of the day (Saturday)

![Peek 29-01-2022 15-53](https://user-images.githubusercontent.com/90012/151665770-9dd51643-ff50-4287-a997-4b2440bf7b14.gif)

The correct one:
![Schermata del 2022-01-29 15-57-39](https://user-images.githubusercontent.com/90012/151665795-8530d692-a5ad-4424-98ca-7d4ef2a157db.png)

thanks!

**Comment by sawhney17** [comment]
Try the latest version :)
