### ISSUE TITLE
Imported events not order by time

### ISSUE THREAD

**Issue by gaga5lala** [sawhney17/logseq-calendars-plugin#11]
Thanks for building the plugin. 

I'm wondering can I import events and order them by time?
![image](https://user-images.githubusercontent.com/3760025/154610416-a31e9a61-1ee3-4376-9481-dd48e1d1791a.png)

Logseq 0.5.9
logseq-calendars-plugin 1.1.6

**Comment by gaga5lala** [comment]
@sawhney17 I created a new calendar to reproduce this issue.

https://calendar.google.com/calendar/ical/d4oh5k57u0m58danrs8eeoohp4%40group.calendar.google.com/private-3702bae1c06004d9e25751f30536b7fe/basic.ics

Seems like it ordered events by created time?

![image](https://user-images.githubusercontent.com/3760025/154634402-3ad62fb1-5da0-4706-b8ae-045af77c7357.png)

**Comment by sawhney17** [comment]
Latest version should fix it. The sample calendar imports properly
<img width="510" alt="Screen Shot 2022-02-18 at 2 11 39 PM" src="https://user-images.githubusercontent.com/80150109/154662479-706f549e-fd92-493c-929c-78e941febf16.png">
