### ISSUE TITLE
It does not work (macOs, iCal)

### ISSUE THREAD

**Issue by mgiugliano** [sawhney17/logseq-calendars-plugin#12]
It worked only once, although after several seconds of delays from the visual "fetching" of the information.

Since that first time, however, it does not work and does not produce any error message.

I would be happy to help you debugging it.

**Comment by sawhney17** [comment]
Does using this link work? Just as a sample. 

https://calendar.google.com/calendar/ical/rao6fvrrsq6mdorf9n30fs6mk4%40group.calendar.google.com/private-18ccd424400ef24c5d343ec93b289590/basic.ics

Are any of your days events recurring? 

Can you try making a blank event? 

Do you get a block appearing and then disappearing? 

And can you make sure you're on the latest version?

**Comment by mgiugliano** [comment]
Thank you for your quick reaction: I am on the latest Logseq and plugin versions.

Events were both recurring but also ad-hoc created: nothing happens. I can't explain why few days ago, it worked (once) and it actually "imported" all the events twice (as if I pressed twice the button). However since then, nothing happens - despite the diagnostic notification on the calendar "fetching".

No block appears. 

I am alo sure the calendar(s) are public, as they are shared with my team mates.

**Comment by sawhney17** [comment]
Does creating just a single blank event work? And you could try downgrading to a version before 2.0.0

**Comment by sawhney17** [comment]
Try the latest version of the plug-in
