### ISSUE TITLE
Confusing "No event for the day detected" for there are all-day events

### ISSUE THREAD

**Issue by sunaiwen** [sawhney17/logseq-calendars-plugin#14]
Hi, I recently want to use Google Calendar to manage my yearly long term plan.

So i set up two events on Google Calendar that are all-day and repeat everyday. The events' setup looks like:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/3401641/155087971-34a17e3e-565d-4366-9de8-c14d96a632fc.png">

But when I click the plugin to sync the events, the name of the calendar in plugin setting would appear but disappear in a very sort time(less than a second), then these messages appear:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/3401641/155088103-91c16395-666d-4cbf-8076-e2dac75af4d1.png">

I open the developer tool, find that there is a http request with data responded:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/3401641/155088748-5b4e41a1-3ad3-4144-ab60-0fba2cca5c1b.png">

**Comment by sawhney17** [comment]
I believe that I haven’t added support for recurring events yet which is likely the root of the issue. If I get the chance I’ll add support for them over the week. As a stepping stone you could try just copy pasting the events for at least this week until I add support for recurring events, or alternatively, you could use the logseq recurrence plugin. Sorry for the inconvenience

**Comment by sawhney17** [comment]
Sorry for the delay, latest version should support this feature!

**Comment by Taapsa** [comment]
Hi!
Still do not get recurring meetings. I do get everything else. Doesn't matter am I the owner of the event or not.

**Comment by sawhney17** [comment]
Even in the latest version? Could you try setting something for like 12 noon just to test. May be a time zone issue

**Comment by Taapsa** [comment]
Hmm, might be something related to time zones. Some of the recurring meetings are popping up. Like the ones which are around 12.

But in the morning, there are two 
one starting 9:30 - 9:45
And next one 9:45 - 10:00

Sometimes the first one appears sometimes not. 
Maybe something with overlapping meetings or when having such "back-to-back" ones?

**Comment by sawhney17** [comment]
Should be fixed now  @Taapsa

**Comment by sawhney17** [comment]
Does the time show up properly when inserting them? If it's possible. Could you also share a link to a sample calendar that showcases this problem.
