### ISSUE TITLE
Import not working for any calendar

### ISSUE THREAD

**Issue by Rumpoled** [sawhney17/logseq-calendars-plugin#18]
I've tried this with all calendar types and can't get the import to work.

**Comment by sawhney17** [comment]
Can you make sure you firstly have events during that day. Secondly. Can you check if you're using recurring events on the day.  Finally, can you check if entering the link you put in settings in browser lead to a file being downloaded

**Comment by Rumpoled** [comment]
Hey, thanks for the quick reply, I've found the [agenda's plugin](https://github.com/haydenull/logseq-plugin-agenda) which gives me this functionality + it picks up todos so I'm going to stick with that though.

Thank you for all the great plugins though! You're find and replace one is really helpful.
