### ISSUE TITLE
Fetching past calendar events

### ISSUE THREAD

**Issue by szlatanos** [sawhney17/logseq-calendars-plugin#2]
After installing the plugin via the marketplace I noticed that it's not possible to fetch past events (using option 3). A feature like this would be awesome. 

Expected behaviour:
- Fetch past events as when clicking the icon to fetch the current date
- Create a notes page with the event for the dates for which a journal page doesn't exist

**Comment by sawhney17** [comment]
How you get this to work for people who don't usually structure their notes in the form of one page per event? What makes the most sense to you? Also, it seems like creating a notes page for every single event across _every_ single calendar event across many years would be unwise to me.

**Comment by szlatanos** [comment]
Apologies, I think my description above was misleading. What I meant with the creation of missing pages was the following: Create a **journal** page after importing past events, for the days for which a journal page doesn't exist. So basically keeping the existing structure but fetching past events on Logseq. 

Another case/example (with the current fetching workflow) is when you don't fetch the events for a few days/don't use loqseq. When fetching the events the next day, the days of inactivity will be completely ignored, both in terms of importing any events occurred as entries, but also in terms of creating a journal page. 

I hope it's more clear now.

**Comment by sawhney17** [comment]
I am hesistant of doing any mass importing. A median option could be that when you’re on a past daily page, you can choose to insert pages there? If the current page is not a daily note page, it will insert notes on today’s page.

**Comment by szlatanos** [comment]
> 

Yes, the suggested solution I think also serves what I mentioned. Thanks a lot for building this plugin.
