### ISSUE TITLE
Installing app causes command palette to crash

### ISSUE THREAD

**Issue by nickriches** [sawhney17/logseq-calendars-plugin#21]
This app is potentially great, but when I run it, there's a conflict with the command palette. Every time I open the palette logseq crashes. Until this behaviour is rectified I am unable to run the plugin.

**Comment by sawhney17** [comment]
Could you test this issue on the latest nightly version?

**Comment by nickriches** [comment]
Thanks. Sorry for late reply. The command palette issue seems to have resolved. Thanks.
