### ISSUE TITLE
Allowing more calendars to be used and option to use JSON for any logseq version

### ISSUE THREAD

**Issue by nickriches** [sawhney17/logseq-calendars-plugin#24]
I have a relatively large number of colour-coded calendars within Google, but the app only seems to allow me to download events from 5 calendars. Could this be expanded? I tried to directly edit the JSON file, to add more calendars, but for later versions of Logseq this doesn't seem to work. Editing the JSON file is far more convenient than using the logseq interface if you are used to this kind of thing. Could there be an option to allow you to select the JSON file, rather than the logseq interface? If you specify more than 5 calendars in the JSON file, will they then all be imported to Logseq?  Thanks.

**Comment by nickriches** [comment]
Is there any further news on this issue? I would love to use the plugin, but the upper limit of 5 calendars is restrictive.

**Comment by nickriches** [comment]
Thanks. But I am not sure how I add more calendars. In my json file I have used the same numbering system:

 "calendar6Name": "🟢 Leisure",
  "calendar6URL": "https://#####################################/basic.ics",

But this calendar is not imported. How can I get more than five calendars to load?

Thanks

N

**Comment by sawhney17** [comment]
If you’re in the latest version, there should automatically be generated a section called account details. If you aren’t seeing it in the Json, add some random content to any of calendar 1, calendar 2 or calendar 3 from within the app.

<img width="1040" alt="Screenshot 2022-05-25 at 3 44 56 PM" src="https://user-images.githubusercontent.com/80150109/170254521-8be4d1b0-7dea-40e1-8fa2-e5d3d9f8cb09.png">

**Comment by sawhney17** [comment]
If you’re in the latest version, there should automatically be generated a section called account details. If you aren’t seeing it in the Json, add some random content to any of calendar 1, calendar 2 or calendar 3 from within the app.

```json
"accountsDetails": {
    "Calendar 1": "https://calendar.google.com/calendar/ical/rao6fvrrsq6mdorf9n30fs6mk4%40group.calendar.google.com/public/basic.ics"
  }```
On 25 May 2022, 11:09 AM +0400, nickriches ***@***.***>, wrote:
> Thanks. But I am not sure how I add more calendars. In my json file I have used the same numbering system:
> "calendar6Name": "🟢 Leisure",
> "calendar6URL": "https://#####################################/basic.ics",
> But this calendar is not imported. How can I get more than five calendars to load?
> Thanks
> N
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>
