### ISSUE TITLE
iCloud Calendars do not work?

### ISSUE THREAD

**Issue by Philipp0205** [sawhney17/logseq-calendars-plugin#25]
Hey there, 
thanks for making the plugin! Everything works like a charm with Google calendar, but when I try to add an iCloud calendar-URL events do not get inserted. 

On icloud.com I get an URL with the format 
webcal://p57-caldav.icloud.com/published/2/.........................................-0

I removed "webcal://". 

Any hints on how to get it to work?

**Comment by sawhney17** [comment]
To test it. Go to to a browser and enter tbr URL. If it downloads a file. Then it's correct.

**Comment by Philipp0205** [comment]
@sawhney17 It downloads the .ics files with all the events in it. The plugin still does not pick up the events for some reason.

**Comment by backyardbiomech** [comment]
When I try to import my icloud calendar events, I get the following error:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/9662673/166291802-83547b7a-5494-4e72-92b7-cc5a63e32643.png">

**Comment by sawhney17** [comment]
The latest update of logseq should fix this issue with crashing.

**Comment by sawhney17** [comment]
Delete webcala rn replace it with https

**Comment by sawhney17** [comment]
Can you check the console for errors?
