### ISSUE TITLE
Complex Title not displayed?

### ISSUE THREAD

**Issue by emms007** [sawhney17/logseq-calendars-plugin#3]
Big thanks for this plugin.

I made a test run using a ICAL from Outlook/Exchange server. 
In the ICS file, the summary of meeting is written down in the following format: `SUMMARY;LANGUAGE=fr:Demo title of a meeting`

This renders in the plugin output as "3:30 PM - 6:30 PM: [object Object]".
Is there a way to have more parameter around the "{Title}" template?

**Comment by sawhney17** [comment]
Hmm, I'll have to investigate this, could you perhaps share some kind of guide as to how to create an ebent with summary in that format? This is how my events look like. <img width="561" alt="Screen Shot 2022-02-01 at 6 06 58 PM" src="https://user-images.githubusercontent.com/80150109/151983234-b3bcadb9-db30-410f-a422-8bd966681f57.png">

Do you have perhaps your language set up as something in specific or something?

**Comment by emms007** [comment]
I am using outlook in a corporate environnement with nothing particular set. I assume the Outlook & Exchange format make it really the far-fetched professional context. 

Looking at the "pi.parseICS(e);" function, it is well understood by the library. It is only a matter of exposing it back to logseq I assume:
![image](https://user-images.githubusercontent.com/171033/151986913-74bd64ff-6c1a-4792-8bc5-9ae76816affb.png)

**Comment by sawhney17** [comment]
Can you try the latest release? Should be fixed

**Comment by sawhney17** [comment]
I've had to revert this in the latest release as it was causing issues with large calendars. Please stay on the current version until I get something working that doesn't interfere with other functions.
