### ISSUE TITLE
icloud  Configuration unsuccessful

### ISSUE THREAD

**Issue by Jenae-Fung** [sawhney17/logseq-calendars-plugin#33]
Following that icloud calendar method didn't work, the plugin and logseq are both the latest version.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/87799513/180349711-abf8c4b6-e44b-465b-8c2e-56d3ab61ce62.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/87799513/180349664-c03d0a6b-48de-4e47-99fa-f4900924d0de.png">
<img width="327" alt="image" src="https://user-images.githubusercontent.com/87799513/180349796-6f749c12-7984-4fd7-bef2-3f91e838ae58.png">

link:p204-caldav.icloud.com.cn/published/2/MjA1NjMyNzg5NTQyMDU2MzLMlKhWUEeIcjIzyh05I78JgDVwWGyP-c2zGw9EC4NEcoc2fuzepAVfz-XVdWZ93F7V3qvYUnVCmwzBejEfmbo
(ps:For testing purposes only)

**Comment by swan14** [comment]
I have not succeeded it with iCloud either until yesterday. But finally I could! The way is to add "http://" before the URL in my case. Try it!

**Comment by Jenae-Fung** [comment]
> I have not succeeded it with iCloud either until yesterday. But finally I could! The way is to add "http://" before the URL in my case. Try it!

Mine worked the same way, thank you very much.
