### ISSUE TITLE
Url to calendar event

### ISSUE THREAD

**Issue by gila2000** [sawhney17/logseq-calendars-plugin#4]
Would it be possible to include a property that is the url of the event in google calendar (to be able to access directly from Logseq)?
Thanks for your great work!

**Comment by sawhney17** [comment]
Not quite sure what you mean by this? You can currently access select the specific calendar using the command pallet, command shift P.

**Comment by gila2000** [comment]
I wonder if it would be possible to create a placeholder in the template to display the url of the event in Google calendar. So, when loading the events in Logseq the url to go to Calendar would appear.

**Comment by gila2000** [comment]
I am thinking of being able to see in Logseq the url of each event shown through the plugin.

**Comment by sawhney17** [comment]
Unfortunately the ics format used does not contain this data. A potential solution is to copy paste the link of the calendar into the description in google calendar when creating the event, this can then be copied. 

I am curious though whether it would be possible for me to integrate what you plan on doing iwth the link into the plugin.
