### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Moilleadoir** [sawhney17/logseq-calendars-plugin#5]
Is there an issue with date formats?  Or some kind of time zone assumption?  When I tried syncing (Google Calendar), it created a new journal page (Feb 4th, 2022, filename: .md), but my journal page for today already exists (4th Feb 2022, filename: 2022_02_04.md).

**Comment by sawhney17** [comment]
Can you make sure you're on the latest version and also that your desired date format is configured in logseq  settings?

**Comment by Moilleadoir** [comment]
I only installed logseq yesterday and installed this plugin from the marketplace about 15 mins before posting. If I create a new journal page it uses my chosen date format.

**Comment by sawhney17** [comment]
THat’s fairly odd. What do you mean by new journal page? Sorry I’m not quite getting you. In which case is it not working?

**Comment by Moilleadoir** [comment]
I mean it doesn’t insert the calendar events on the current journal page, it creates a new one with no name, just an .md extension.  If I open that from the Recent list it has the date format in the default (US) format.

**Comment by sawhney17** [comment]
Could you perhaps record a video? That'll help me better dial in the bug.

**Comment by Moilleadoir** [comment]
Video files seem to be too big for github - the upload limit is 10 MB, but my file is 50 MB.  I’ll see if I can crop it.
